ToDolist.Application/EndPoint.Site/Controllers/AnalyzController.cs
using Application.Interfaces.Context;
using Application.Interfaces.FacadPatterns;
using Application.Services.TodoItem.Queries.GetCountForAnalyz;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace EndPoint.Site.Controllers
{
    [Authorize]
    public class AnalyzController : Controller
    {
        private readonly IDataBaseContext DB;
        private readonly ICartFacad CF;
        public AnalyzController(ICartFacad cF ,IDataBaseContext dB)
        {
            DB = dB;
            CF = cF;
        }

        public IActionResult index( )
        {
            ViewBag.suspend = DB.StatusInCarts.Count(x => x.StatusId == 1);
            ViewBag.Nostart = DB.StatusInCarts.Count(x => x.StatusId == 2); ;
            ViewBag.InProgress = DB.StatusInCarts.Count(x => x.StatusId == 3);
            ViewBag.isComplete = DB.StatusInCarts.Count(x => x.StatusId == 4);
            ViewBag.General = DB.PriorityInCarts.Count(p => p.PriorityId == 1);
            ViewBag.Urgent = DB.PriorityInCarts.Count(p => p.PriorityId == 2);
            ViewBag.Critical = DB.PriorityInCarts.Count(p => p.PriorityId == 3);
            return View();
            //try
            //{
            //var result = CF.GetCountAnalyzForService.Excute();
            //return View(result);

            //}
            //catch (Exception e)
            //{
            //    throw new Exception(e.ToString());
            //}
        }
       
    }
}

ToDolist.Application/EndPoint.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html >
<html  dir="rtl" lang="fa">
<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"] | TODO وب اپلیکیشین </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/SiteTemplate/css/StyleIndex.css" />
    <link rel="stylesheet" href="https://unpkg.com/@@majidh1/jalalidatepicker/dist/jalalidatepicker.min.css">
    <link rel="stylesheet" href="~/SiteTemplate/css/style.css">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css' rel='stylesheet'>
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>     
    <link href="~/sweetalert/sweetalert2.css" rel="stylesheet" />
    <link href="~/sweetalert/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/waitme/waitme.min.css" rel="stylesheet" />


</head >
<body dir="rtl" >
    <div class="sidebar1">
         <nav class="sidebar close">
           
        <header>
            <div class="image-text">
                <span class="image">
                   <img src="~/SiteTemplate/img/ToDo-List-icon.png">

                </span>
                <div class="text logo-text">
                    <span class="name" style="font-family: 'Pacifico', cursive;">ToDo</span>
                    <span class="profession" > ثبت وظایف شما</span>
                </div>


            </div>


            <i class='bx bx-chevron-right toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">

                <li class="search-box" hidden>
                    <i class="bx bx-search icon"></i>
                    <input type="text" placeholder="جستجو...">
                </li>

                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="/home">
                            <i class='bx bx-home-alt icon' ></i>
                            <span class="text nav-text"  >وظایف</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a asp-controller="ToDo" asp-action="index">
                            <i class='bx bx-task icon' ></i>
                            <span   class="text nav-text">ساخت وظیفه جدید </span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-bell icon'></i>
                            <span class="text nav-text">اعلان ها</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a  asp-controller="Analyz" asp-action="index">
                            <i  class='bx bx-pie-chart-alt icon' ></i>
                            <span  class="text nav-text">آنالیز</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-heart icon' ></i>
                            <span class="text nav-text">Likes</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-wallet icon' ></i>
                            <span class="text nav-text">Wallets</span>
                        </a>
                    </li>

                </ul>
            </div>

            <div class="bottom-content">
                <li >
                    <a asp-controller="Account" asp-action="Logout">
                        <i class='bx bx-log-out icon' ></i>
                        <span class="text nav-text" >خروج</span>
                    </a>
                </li>

                <li class="mode">
                    <div class="sun-moon">
                        <i class='bx bx-moon icon moon'></i>
                        <i class='bx bx-sun icon sun'></i>
                    </div>
                    <span class="mode-text text" >شب</span>

                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>
                </li>

            </div>
        </div>

    </nav>
    </div>
   

    @RenderBody()

        <!--اسکریپت -->
          <script src="/SiteTemplate/js/ScriptIndex.js"></script> 
          <script src="~/SiteTemplate/js/main.js"></script>
          <script src="~/SiteTemplate/js/SideBar.js"></script>
          <script src="~/waitme/waitme.min.js"></script>
          <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
          <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
          <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
          <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
          <script src="~/lib/jquery-validation/dist/jquery.unobtrusive-ajax.js"></script>
          <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
          <script type="text/javascript" src="https://unpkg.com/@@majidh1/jalalidatepicker/dist/jalalidatepicker.min.js"></script>       
          <script src="~/sweetalert/sweetalert2.all.js"></script>
          <script src="~/sweetalert/sweetalert2.all.min.js"></script>
          <script src="~/sweetalert/sweetalert2.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
          <script src="~/sitetemplate/js/microsoft-signalr.js"></script>
          <script src="~/signalr/dist/browser/signalr.min.js"></script>
<script>
        jalaliDatepicker.startWatch({
          minDate: "attr",
          maxDate: "attr",
          minTime: "attr",
          maxTime: "attr",
          persianDigits: true,
          changeMonthRotateYear: true,
          showTodayBtn: true,
          showEmptyBtn: true,
          topSpace: 10,
          bottomSpace: 30,
          dayRendering(opt,input){
              return {
                  isHollyDay:opt.day==1
              }
          }
        });

        document.getElementById("aaa").addEventListener("jdp:change", function (e) { console.log(e) });
        </script>
        <script>
            var connection =new signalR.HubConnectionBuilder().withUrl("/notify").withAutomaticReconnect().build();
            connection.start().catch(function(err)
            {
                return console.error(err)
            });
            connection.on("getNofication",function (data){
                browsernotify(data);
            });
        </script>

</body>
@RenderSection("Scripts", false)
@RenderSection("Modals",false)
@RenderSection("script",false)
</html>    

ToDolist.Application/EndPoint.Site/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>